### ISSUE TITLE
Feature Request: Builtin swap left,right and highlight swaps

### ISSUE THREAD

**Issue by vunhatchuong** [aaronik/treewalker.nvim#16]
What do you think about builtin the functionality of swapping left and right, and highlighting the 2 swapped parts?

If you agree I can try to make a PR if possible.

**Comment by aaronik** [comment]
Hey, thanks for the issue! I hope you're enjoying the plugin 😀👍

I've definitely thought about both of these things, and have concluded that:

1) The plugin doesn't need to build in left and right swaps. This functionality already exists perfectly in at least the two other plugins referenced at the bottom of the readme, probably more. No need to reimplement it here - just leaves more room for bugs, or creates the need for dependencies that the plugin core functionality doesn't need.

2) the highlighting is for a degree of visual feedback for where the cursor has moved to. But swapping already is that visual feedback - you know what happened by virtue of your code having moved around. Additionally, I saw examples of the swapping highlighting both nodes, and tbh with you it kind of just seemed busy. It ultimately just didn't do it for me. Seemed unnecessary. So that's why it's not here now.

So these are both good ideas - I had them too, but ultimately decided against them.

Thanks again for the ideas, and I hope you continue to enjoy the plugin despite me not wanting to do these two things!

Please keep on ideating about how it could be better though! You'll probably come up with something that I missed and then I'm definitely open to contributions!

**Comment by aaronik** [comment]
@vunhatchuong Just wanted to drop a line and let you know that left/right swapping is now available in the plugin! Please feel free to let me know if you try it out and it's working for you, or if you find any problems with it. Thanks!

**Comment by vunhatchuong** [comment]
@aaronik Hi thanks for the implementation, one limitation I see is that it doesn't swap the params.

For example in the code below, I should be able to place my  cursor on `"K"` and use `SwapRight` to put `"K"` as the 2nd argument rather than the first.

```lua
heads = {
    { "k", "<CMD>Treewalker SwapUp<CR>", { desc = "up" } },
}
```

**Comment by aaronik** [comment]
Ah, I see. The way it's currently coded is that you need to be at the beginning of the node, so you'd have to put your cursor at the first `"` on that middle line, _then_ run `SwapRight`.

But you're right, I feel like it should know somehow. I'll have to think about that one.

Thanks for giving it a spin and letting me know your findings! It's exactly this kind of oversight that having other people test it helps to discover :)

**Comment by aaronik** [comment]
> Hi, is it intentional that if you on `"j"` and then swap left, it will swap with the whole element 1? If yes then it's all good.
> 
> ```lua
> heads = {
>     { "k", "<CMD>Treewalker SwapUp<CR>", { desc = "up" } },
>     { "j", "<CMD>Treewalker SwapDown<CR>", { desc = "down" } },
> }
> ```

Yeah this is the outcome of the way it's implemented. Does that seem like a reasonable way for it to work to you?

**Comment by vunhatchuong** [comment]
Yeah, makes sense. Thanks.

Maybe I should make a separate issue, but do you think it's a good idea to have an option to make the cursor stay in place? So, instead of going **with**  the swapped element, it stays.

So if you `SwapRight` two times the node will get back to its original position.

**Comment by aaronik** [comment]
Oh, interesting! No I don't think that's going to be on the roadmap, but it's clever thinking. I think this way makes more sense, and I'd rather the plugin be just predictable and easy than have a million options and configurations. I'm a "less is more" kind of guy when it comes to options :)
